CREATE DATABASE IF NOT EXISTS myfile;

USE myfile;

CREATE TABLE IF NOT EXISTS role
(
	Id SMALLINT NOT NULL UNIQUE AUTO_INCREMENT,
	Remark VARCHAR(255) NOT NULL,
	PRIMARY KEY (Id)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS users
(
	Id VARCHAR(255) NOT NULL UNIQUE,
	RoleId SMALLINT NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL,
	Name VARCHAR(255),
	LastLoginTime TIMESTAMP NOT NULL DEFAULT NOW(),
	LastLoginIP VARCHAR(255) NOT NULL DEFAULT '127.0.0.1',
	PRIMARY KEY (Id),
	FOREIGN KEY (RoleId) REFERENCES role(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS current_logged_users
(
	Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	UserId VARCHAR(255) NOT NULL UNIQUE,
	CurrentIPAddress VARCHAR(255) NOT NULL,
	CurrentLoginTime TIMESTAMP NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (UserId) REFERENCES users(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

DELIMITER |

CREATE TRIGGER after_current_logged_users_insert BEFORE INSERT ON current_logged_users
FOR EACH ROW
BEGIN
	UPDATE users
	SET LastLoginTime = NEW.CurrentLoginTime,
		LastLoginIP = NEW.CurrentIPAddress
	WHERE Id = NEW.UserId;
END;
|

DELIMITER ;

CREATE TABLE IF NOT EXISTS file_type
(
	Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	Remark VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (Id)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS files
(
	Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	FileTypeId BIGINT,
	FilePath TEXT NOT NULL,
	LastCreatedTime TIMESTAMP NOT NULL,
	LastModifiedTime TIMESTAMP NOT NULL DEFAULT NOW(),
	InputFlag TINYINT(1) NOT NULL,
	OutputFlag TINYINT(1) NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (FileTypeId) REFERENCES file_type(Id) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT CHK_InputOutputFlag CHECK ((InputFlag = 0 AND InputFlag = 1) OR (InputFlag = 1 AND InputFlag = 0))
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS job_type
(
	Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	Remark VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (Id)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS jobs
(
	Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	JobTypeId BIGINT,
	Remark VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (Id),
	FOREIGN KEY (JobTypeId) REFERENCES job_type(Id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS jobs_operation
(
	Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	JobsId BIGINT,
	InputFileTypeId BIGINT,
	OutputFileTypeId BIGINT,
	FileJobFlag TINYINT(1) NOT NULL,
	CommonJobFlag TINYINT(1) NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (JobsId) REFERENCES Jobs(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (InputFileTypeId) REFERENCES file_type(Id) ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (OutputFileTypeId) REFERENCES file_type(Id) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT CHK_JobFlag CHECK ((FileJobFlag = 0 AND FileJobFlag = 1) OR (FileJobFlag = 1 AND FileJobFlag = 0))
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS files_list
(
	Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	JobsOperationId BIGINT, 
	FilesId BIGINT,
	PRIMARY KEY (Id),
	FOREIGN KEY (JobsOperationId) REFERENCES jobs_operation(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (FilesId) REFERENCES Files(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS user_logs
(
	Id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	UsersId VARCHAR(255),
	JobsOperationId BIGINT,
	TimeLog TIMESTAMP NOT NULL DEFAULT NOW(),
	IPAddressLog VARCHAR(255) NOT NULL DEFAULT '127.0.0.1',
	PRIMARY KEY (Id),
	FOREIGN KEY (UsersId) REFERENCES users(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (JobsOperationId) REFERENCES jobs_operation(Id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;




